# Generated by Django 4.2.2 on 2023-07-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
    ]
