# Generated by Django 4.2.2 on 2023-06-28 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_profile_slug_alter_profile_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='middle_Name',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_Photo',
            new_name='profile_photo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='passing_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
