# Generated by Django 4.2.2 on 2023-07-06 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0002_initial'),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Selected_applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selected',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Selected_job', to='recruiter.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Job_Skills', to='candidate.skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Posting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicants',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicants',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applicants', to='recruiter.job'),
        ),
    ]
