# Generated by Django 4.2.2 on 2023-06-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicants',
            old_name='Applied_At',
            new_name='applied_At',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='About_Company',
            new_name='about_Company',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Job_description',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='No_Of_Opening',
            new_name='no_Of_Opening',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Posted_At',
            new_name='posted_At',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Salary',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Skills_required',
            new_name='skills_required',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Updated_At',
            new_name='updated_At',
        ),
    ]
