# Generated by Django 4.2.2 on 2023-06-22 11:17

from django.db import migrations, models
import recruiter.models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_profile_slug_alter_profile_experience_and_more'),
        ('recruiter', '0002_rename_applied_at_applicants_applied_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='no_Of_Opening',
            new_name='no_of_openings',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='candidate.skill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='In Lacs/Annum', max_digits=5, validators=[recruiter.models.validate_salary]),
        ),
    ]
