# Generated by Django 4.2.2 on 2023-06-21 07:28

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_rename_applied_at_applicants_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
