# Generated by Django 4.2.2 on 2023-06-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_job_city_job_slug_remove_job_skills_job_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicants',
            old_name='applied_At',
            new_name='applied_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='about_Company',
            new_name='about_company',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='posted_At',
            new_name='posted_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='updated_At',
            new_name='updated_at',
        ),
    ]
